grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - devops-monitor-le.darienc.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - devops-monitor-le.darienc.com
        secretName: grafana-tls

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100

prometheus:
  prometheusSpec:
    retention: 7d
