apiVersion: v1
kind: Secret
metadata:
  name: openwebui-db-url
  namespace: llm
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOkRhcmllbnQxMjNAcG9zdGdyZXNxbC5sbG0uc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9vcGVud2VidWk=
